(()=>{
'use strict';
const LANG={en:['English','EN','en-GB'],ca:['Catalan','CA','ca-ES'],es:['Spanish','ES','es-ES'],fr:['French','FR','fr-FR'],de:['German','DE','de-DE'],it:['Italian','IT','it-IT'],pt:['Portuguese','PT','pt-PT'],eu:['Basque','EU','eu-ES'],cy:['Welsh','CY','cy-GB'],gd:['Scottish Gaelic','GD','gd-GB'],ar:['Arabic','AR','ar-SA'],ja:['Japanese','JA','ja-JP']};
const KEY=['hub','intro','topic','hint','make','loading','error','choose','check','retry','yes','guided','free','compare','model','again','next','save','saved','listen','reveal','done','back','scenario','other','your','cue','self','works','repeat','turn','swap','rescue','lines'];
const TEXT={
en:['Build your confidence','Short activities to turn familiar words into useful language.','What would you like to talk about?','For example: speaking to a neighbour','Create my practice','Preparing your practice…','Could not create this practice. Try again.','Choose a reply','Check','Try again.','Correct!','Now type the reply. The first word is shown.','Reply on your own. Other natural answers can work.','Compare with a model reply','One possible reply','Practise again','Next situation','Save phrase','Saved','Listen','Show example','Finished! Choose another topic or activity.','Back to LingoTotal','Situation','Other person says','Your reply','Change this detail','Does your answer communicate the same idea?','My answer works','I will practise again','Complete a conversation: choose, practise, then reply on your own.','Change one detail in a useful sentence.','Keep a conversation going when something goes wrong.','Complete a three-line conversation.'],
ca:['Guanya confiança','Activitats breus per convertir paraules conegudes en llengua útil.','De què t’agradaria parlar?','Per exemple: parlar amb un veí','Crea la pràctica','Preparant la pràctica…','No s’ha pogut crear. Torna-ho a provar.','Tria una resposta','Comprova','Torna-ho a provar.','Correcte!','Ara escriu la resposta. Es mostra la primera paraula.','Respon pel teu compte. Altres respostes naturals poden funcionar.','Compara-la amb una resposta model','Una resposta possible','Torna a practicar','Situació següent','Desa la frase','Desada','Escolta','Mostra un exemple','Has acabat! Tria un altre tema o activitat.','Torna a LingoTotal','Situació','L’altra persona diu','La teva resposta','Canvia aquest detall','La teva resposta comunica la mateixa idea?','La meva resposta funciona','Tornaré a practicar','Completa una conversa: tria, practica i respon pel teu compte.','Canvia un detall d’una frase útil.','Mantén la conversa quan hi ha un imprevist.','Completa una conversa de tres frases.'],
es:['Gana confianza','Actividades breves para convertir palabras conocidas en lenguaje útil.','¿De qué te gustaría hablar?','Por ejemplo: hablar con un vecino','Crear práctica','Preparando la práctica…','No se pudo crear. Inténtalo de nuevo.','Elige una respuesta','Comprobar','Inténtalo de nuevo.','¡Correcto!','Ahora escribe la respuesta. Se muestra la primera palabra.','Responde por tu cuenta. Otras respuestas naturales pueden funcionar.','Compara con una respuesta modelo','Una respuesta posible','Practicar otra vez','Siguiente situación','Guardar frase','Guardada','Escuchar','Mostrar ejemplo','¡Has terminado! Elige otro tema o actividad.','Volver a LingoTotal','Situación','La otra persona dice','Tu respuesta','Cambia este detalle','¿Tu respuesta comunica la misma idea?','Mi respuesta funciona','Practicaré otra vez','Completa una conversación: elige, practica y responde por tu cuenta.','Cambia un detalle de una frase útil.','Mantén la conversación cuando surge un imprevisto.','Completa una conversación de tres frases.'],
fr:['Gagnez en confiance','De courtes activités pour utiliser les mots que vous connaissez.','De quoi aimeriez-vous parler ?','Par exemple : parler à un voisin','Créer mon activité','Préparation de l’activité…','Impossible de créer l’activité. Réessayez.','Choisissez une réponse','Vérifier','Réessayez.','Correct !','Écrivez la réponse. Le premier mot est indiqué.','Répondez seul. D’autres réponses naturelles sont possibles.','Comparez avec une réponse modèle','Une réponse possible','Recommencer','Situation suivante','Enregistrer','Enregistrée','Écouter','Voir un exemple','Terminé ! Choisissez un autre sujet ou une autre activité.','Retour à LingoTotal','Situation','L’autre personne dit','Votre réponse','Changez ce détail','Votre réponse exprime-t-elle la même idée ?','Ma réponse convient','Je vais réessayer','Complétez une conversation : choisissez, entraînez-vous et répondez seul.','Changez un détail dans une phrase utile.','Poursuivez la conversation en cas de problème.','Complétez une conversation en trois répliques.'],
de:['Sicherer werden','Kurze Übungen, um bekannte Wörter zu verwenden.','Worüber möchten Sie sprechen?','Zum Beispiel: mit Nachbarn sprechen','Übung erstellen','Übung wird vorbereitet…','Die Übung konnte nicht erstellt werden. Bitte erneut versuchen.','Antwort auswählen','Prüfen','Bitte erneut versuchen.','Richtig!','Schreiben Sie die Antwort. Das erste Wort wird angezeigt.','Antworten Sie selbst. Andere natürliche Antworten sind möglich.','Mit einer Modellantwort vergleichen','Eine mögliche Antwort','Noch einmal üben','Nächste Situation','Satz speichern','Gespeichert','Anhören','Beispiel zeigen','Fertig! Wählen Sie ein neues Thema oder eine andere Übung.','Zurück zu LingoTotal','Situation','Die andere Person sagt','Ihre Antwort','Ändern Sie dieses Detail','Drückt Ihre Antwort denselben Gedanken aus?','Meine Antwort passt','Ich übe noch einmal','Gespräch ergänzen: auswählen, üben und selbst antworten.','Ändern Sie ein Detail in einem nützlichen Satz.','Halten Sie ein Gespräch bei Problemen am Laufen.','Vervollständigen Sie ein Gespräch mit drei Zeilen.'],
it:['Prendi sicurezza','Attività brevi per usare le parole che già conosci.','Di che cosa vorresti parlare?','Per esempio: parlare con un vicino','Crea l’attività','Preparazione dell’attività…','Impossibile creare l’attività. Riprova.','Scegli una risposta','Controlla','Riprova.','Esatto!','Scrivi la risposta. Viene mostrata la prima parola.','Rispondi da solo. Sono possibili altre risposte naturali.','Confronta con una risposta modello','Una risposta possibile','Esercitati di nuovo','Situazione successiva','Salva la frase','Salvata','Ascolta','Mostra un esempio','Hai finito! Scegli un altro argomento o attività.','Torna a LingoTotal','Situazione','L’altra persona dice','La tua risposta','Cambia questo dettaglio','La tua risposta comunica la stessa idea?','La mia risposta va bene','Mi eserciterò ancora','Completa una conversazione: scegli, esercitati e rispondi da solo.','Cambia un dettaglio in una frase utile.','Mantieni viva la conversazione quando nasce un problema.','Completa una conversazione di tre battute.'],
pt:['Ganhe confiança','Atividades curtas para usar as palavras que já conhece.','Sobre o que gostaria de falar?','Por exemplo: falar com um vizinho','Criar atividade','A preparar a atividade…','Não foi possível criar a atividade. Tente novamente.','Escolha uma resposta','Verificar','Tente novamente.','Correto!','Escreva a resposta. A primeira palavra é mostrada.','Responda por si. Outras respostas naturais são possíveis.','Compare com uma resposta modelo','Uma resposta possível','Praticar novamente','Situação seguinte','Guardar frase','Guardada','Ouvir','Mostrar exemplo','Terminou! Escolha outro tema ou atividade.','Voltar ao LingoTotal','Situação','A outra pessoa diz','A sua resposta','Mude este detalhe','A sua resposta transmite a mesma ideia?','A minha resposta funciona','Vou praticar novamente','Complete uma conversa: escolha, pratique e responda por si.','Mude um detalhe numa frase útil.','Mantenha a conversa quando surge um problema.','Complete uma conversa de três falas.'],
eu:['Hartu konfiantza','Ezagutzen dituzun hitzak erabiltzeko jarduera laburrak.','Zeri buruz hitz egin nahi duzu?','Adibidez: auzoko batekin hitz egitea','Sortu ariketa','Ariketa prestatzen…','Ezin izan da ariketa sortu. Saiatu berriro.','Aukeratu erantzuna','Egiaztatu','Saiatu berriro.','Ondo!','Idatzi erantzuna. Lehen hitza erakusten da.','Erantzun zeure kabuz. Beste erantzun natural batzuk ere badaude.','Alderatu ereduzko erantzunarekin','Erantzun posible bat','Praktikatu berriro','Hurrengo egoera','Gorde esaldia','Gordeta','Entzun','Erakutsi adibidea','Amaitu duzu! Aukeratu beste gai edo jarduera bat.','Itzuli LingoTotalera','Egoera','Beste pertsonak dio','Zure erantzuna','Aldatu xehetasun hau','Zure erantzunak ideia bera adierazten du?','Nire erantzunak balio du','Berriro praktikatuko dut','Osatu elkarrizketa: aukeratu, praktikatu eta erantzun zeure kabuz.','Aldatu xehetasun bat esaldi erabilgarri batean.','Jarraitu hizketan arazo bat sortzen denean.','Osatu hiru lerroko elkarrizketa.'],
cy:['Meithrin hyder','Gweithgareddau byr i ddefnyddio geiriau rydych eisoes yn eu gwybod.','Am beth hoffech chi siarad?','Er enghraifft: siarad â chymydog','Creu ymarfer','Yn paratoi’r ymarfer…','Ni ellid creu’r gweithgaredd. Rhowch gynnig arall.','Dewiswch ateb','Gwirio','Rhowch gynnig arall.','Cywir!','Teipiwch yr ateb. Dangosir y gair cyntaf.','Atebwch ar eich pen eich hun. Gall atebion eraill weithio.','Cymharwch ag ateb enghreifftiol','Un ateb posibl','Ymarfer eto','Sefyllfa nesaf','Cadw’r frawddeg','Wedi’i chadw','Gwrando','Dangos enghraifft','Gorffen! Dewiswch bwnc neu weithgaredd arall.','Yn ôl i LingoTotal','Sefyllfa','Mae’r person arall yn dweud','Eich ateb','Newidiwch y manylyn hwn','A yw eich ateb yn cyfleu’r un syniad?','Mae fy ateb yn gweithio','Byddaf yn ymarfer eto','Cwblhewch sgwrs: dewiswch, ymarferwch ac atebwch ar eich pen eich hun.','Newidiwch un manylyn mewn brawddeg ddefnyddiol.','Cadwch y sgwrs i fynd pan fydd problem.','Cwblhewch sgwrs tair llinell.'],
gd:['Tog misneachd','Gnìomhan goirid gus faclan aithnichte a chleachdadh.','Cò mu dheidhinn a bu toil leat bruidhinn?','Mar eisimpleir: bruidhinn ri nàbaidh','Cruthaich eacarsaich','Ag ullachadh na h-eacarsaich…','Cha b’ urrainn an eacarsaich a chruthachadh. Feuch a-rithist.','Tagh freagairt','Dearbhaich','Feuch a-rithist.','Ceart!','Sgrìobh an fhreagairt. Chithear a’ chiad fhacal.','Freagair leat fhèin. Faodaidh freagairtean eile obrachadh.','Dèan coimeas ri freagairt mhodail','Freagairt a dh’fhaodadh a bhith ann','Cleachd a-rithist','An ath shuidheachadh','Sàbhail abairt','Sàbhailte','Èist','Seall eisimpleir','Deiseil! Tagh cuspair no gnìomh eile.','Air ais gu LingoTotal','Suidheachadh','Tha an neach eile ag ràdh','Do fhreagairt','Atharraich am mion-fhiosrachadh seo','A bheil an aon bheachd nad fhreagairt?','Tha mo fhreagairt freagarrach','Cleachdaidh mi a-rithist','Cuir crìoch air còmhradh: tagh, cleachd agus freagair leat fhèin.','Atharraich aon mhion-fhiosrachadh ann an seantans fheumail.','Cùm an còmhradh a’ dol nuair a thig duilgheadas.','Cuir crìoch air còmhradh trì loidhnichean.'],
ar:['عزّز ثقتك','أنشطة قصيرة لاستخدام الكلمات التي تعرفها.','عمّ تود التحدث؟','مثلاً: التحدث إلى جار','أنشئ التمرين','جارٍ إعداد التمرين…','تعذر إنشاء النشاط. حاول مرة أخرى.','اختر ردًا','تحقق','حاول مرة أخرى.','صحيح!','اكتب الرد. تظهر الكلمة الأولى.','أجب بنفسك. قد توجد ردود طبيعية أخرى.','قارن بردّ نموذجي','ردّ ممكن','تدرّب مجددًا','الموقف التالي','احفظ العبارة','محفوظة','استمع','أظهر مثالاً','أكملت النشاط! اختر موضوعًا أو نشاطًا آخر.','العودة إلى LingoTotal','الموقف','يقول الطرف الآخر','ردك','غيّر هذا التفصيل','هل يوصل ردك المعنى نفسه؟','ردي مناسب','سأتدرّب مجددًا','أكمل محادثة: اختر وتدرّب ثم أجب بنفسك.','غيّر تفصيلاً واحدًا في جملة مفيدة.','أبقِ المحادثة مستمرة عند حدوث مشكلة.','أكمل محادثة من ثلاثة أسطر.'],
ja:['自信をつけよう','知っている言葉を使えるようにする短い練習です。','何について話したいですか？','例：近所の人と話す','練習を作る','練習を準備中…','作成できませんでした。もう一度お試しください。','返事を選ぶ','確認','もう一度試してください。','正解！','返事を入力します。最初の語が表示されます。','自分で答えましょう。自然な答えはほかにもあります。','お手本と比べる','答えの一例','もう一度練習','次の場面','フレーズを保存','保存済み','聞く','例を表示','完了です！別の話題や活動を選んでください。','LingoTotalに戻る','場面','相手の言葉','あなたの返事','この部分を変える','あなたの答えは同じ意味を伝えていますか？','自分の答えで伝わる','もう一度練習する','会話を完成：選び、練習し、自分で答えます。','便利な文の一部を変えます。','困ったときも会話を続けます。','3行の会話を完成します。']
};
const params=new URLSearchParams(location.search),ALIASES={english:'en',catalan:'ca',spanish:'es',french:'fr',german:'de',italian:'it',portuguese:'pt',basque:'eu',welsh:'cy',gaelic:'gd',arabic:'ar',japanese:'ja'};
function lang(v,f){const s=String(v||'').trim().toLowerCase(),b=s.split('-')[0];return LANG[s]?s:LANG[b]?b:ALIASES[s]||f}
const ui=lang(params.get('ui')||localStorage.getItem('lingototal_ui_language'),'en'),target=lang(params.get('target')||localStorage.getItem('lingototal_target_language'),'es'),mode=document.body.dataset.mode||'hub',t=k=>(TEXT[ui]||TEXT.en)[KEY.indexOf(k)]||k,$=s=>document.querySelector(s);
document.documentElement.lang=ui;document.documentElement.dir=ui==='ar'?'rtl':'ltr';localStorage.setItem('lingototal_ui_language',ui);localStorage.setItem('lingototal_target_language',LANG[target][0]);
const names={turn:'LingoTurn',swap:'LingoSwap',rescue:'LingoRescue',lines:'LingoThree Lines'},paths={turn:'lingoturn.html',swap:'lingoswap.html',rescue:'lingorescue.html',lines:'lingothreelines.html'},url=p=>p+'?'+new URLSearchParams({ui,target});
document.querySelectorAll('.home').forEach(a=>a.href=url('index.html'));$('.back').href=url(mode==='hub'?'index.html':'lingobasics.html');$('.back').textContent=mode==='hub'?t('back'):t('hub');$('.pair').textContent=LANG[ui][1]+' → '+LANG[target][1];$('#title').textContent=mode==='hub'?t('hub'):names[mode];$('#lead').textContent=t(mode==='hub'?'intro':mode);
if(mode==='hub'){for(const key of Object.keys(names)){const a=document.createElement('a');a.className='card';a.href=url(paths[key]);const h=document.createElement('h2'),p=document.createElement('p'),arrow=document.createElement('span');h.textContent=names[key];p.textContent=t(key);arrow.className='arrow';arrow.textContent='→';a.append(h,p,arrow);$('#cards').append(a)}return}
const uiNodes={topic:'topic',make:'make',check:'check',reveal:'reveal',again:'again',next:'next',save:'save',listen:'listen'};for(const [id,key] of Object.entries(uiNodes))if(id!=='topic')$('#'+id).textContent=t(key);$('#topicLabel').textContent=t('topic');$('#topic').placeholder=t('hint');
let items=[],index=0,stage=0,picked='',speech=null,playId=0;
const TURN_TEXT={en:['Write up to four words to begin the reply.','Show the whole phrase','Now write your own reply.','Compare my reply','Your reply uses the model phrase.','Compare your reply with the model. Check the words or meaning that differ; another natural reply may also work.','Your reply','Speak and compare','Stop recording','Listen to your recording and the model. Decide what you want to change.','Microphone unavailable. You can still listen to the model.','Restart'],ca:['Escriu fins a quatre paraules per començar la resposta.','Mostra la frase sencera','Ara escriu la teva resposta.','Compara la meva resposta','La teva resposta coincideix amb la frase model.','Compara la teva resposta amb el model. Revisa les paraules o el significat diferents; una altra resposta natural també pot funcionar.','La teva resposta','Parla i compara','Atura la gravació','Escolta la teva gravació i el model. Decideix què vols canviar.','Micròfon no disponible. Encara pots escoltar el model.','Recomença'],es:['Escribe hasta cuatro palabras para empezar la respuesta.','Mostrar la frase completa','Ahora escribe tu propia respuesta.','Comparar mi respuesta','Tu respuesta coincide con la frase modelo.','Compara tu respuesta con el modelo. Revisa las palabras o el significado diferentes; otra respuesta natural también puede funcionar.','Tu respuesta','Hablar y comparar','Detener grabación','Escucha tu grabación y el modelo. Decide qué quieres cambiar.','Micrófono no disponible. Puedes escuchar el modelo.','Reiniciar']};
const tt=i=>(TURN_TEXT[ui]||TURN_TEXT.en)[i];
let recorder=null,recordStream=null,recordUrl=null;
function stopRecord(){if(recorder?.state==='recording')recorder.stop();recordStream?.getTracks().forEach(track=>track.stop());recordStream=null}
function clearRecording(){stopRecord();if(recordUrl)URL.revokeObjectURL(recordUrl);recordUrl=null;$('#turnAudio')?.remove();$('#turnRecordStatus')?.remove();$('#turnRecord').textContent=tt(7)}
async function recordTurn(){if(recorder?.state==='recording'){stopRecord();return}clearRecording();try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});recordStream=stream;const chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=()=>{stream.getTracks().forEach(track=>track.stop());recordStream=null;if(!chunks.length)return;recordUrl=URL.createObjectURL(new Blob(chunks,{type:recorder.mimeType||'audio/webm'}));const audio=document.createElement('audio');audio.id='turnAudio';audio.controls=true;audio.src=recordUrl;$('#turnRecord').after(audio);const note=document.createElement('p');note.id='turnRecordStatus';note.textContent=tt(10);audio.after(note);$('#turnRecord').textContent=tt(7)};recorder.start();$('#turnRecord').textContent=tt(8)}catch{const note=document.createElement('p');note.id='turnRecordStatus';note.textContent=tt(11);$('#turnRecord').after(note)}}
if(mode==='turn'){const button=document.createElement('button');button.id='turnRecord';button.type='button';button.textContent=tt(7);button.onclick=recordTurn;$('#listenModel').after(button)}
function norm(x){return String(x||'').normalize('NFKC').toLocaleLowerCase(LANG[target][2]).replace(/[\p{P}\p{S}]/gu,'').replace(/\s+/g,' ').trim()}
const instructions={
turn:'Each case: situation (interface language), partner (target language), answer (short target-language reply), meaning (interface language), options (exactly three distinct target-language replies including answer; other two clearly unsuitable).',
swap:'Each case: situation (interface language), model (short target-language sentence), cue (one changed detail in interface language), answer (new target-language sentence with just that detail changed), meaning (interface language).',
rescue:'Each case: situation (a small communication problem in interface language), partner (target language), answer (helpful short repair reply in target language), meaning (interface language), options (exactly three distinct target-language replies including answer; other two clearly unhelpful).',
lines:'Each case: situation (interface language), opening (first line in target language), answer (learner reply in target language), closing (other speaker follow-up in target language), meaning (interface language).'
};
function prompt(topic){return 'Create exactly THREE varied, short, coherent everyday exercises for false beginners (A1-A2). Learner topic: '+topic+'. Interface language: '+LANG[ui][0]+'. Target language: '+LANG[target][0]+'. Activity: '+names[mode]+'. '+instructions[mode]+' Keep every case strictly on the learner topic. All context, cues and meanings ONLY in interface language. All dialogue and options ONLY in target language. Use common vocabulary and fully grammatical sentences. Avoid explanations, markdown, alternatives. Return ONLY JSON: {"cases":[...]}.'}
function parse(data){const text=data?.text||data?.content||data?.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'',a=String(text).indexOf('{'),b=String(text).lastIndexOf('}');return JSON.parse(String(text).slice(a,b+1))}
function validate(data){if(!Array.isArray(data?.cases)||data.cases.length<3)throw Error('cases');return data.cases.slice(0,3).map(c=>{const required=mode==='swap'?['situation','model','cue','answer','meaning']:mode==='lines'?['situation','opening','answer','closing','meaning']:['situation','partner','answer','meaning','options'];if(required.some(k=>k==='options'?!Array.isArray(c[k])||c[k].length!==3:typeof c[k]!=='string'||!c[k].trim()))throw Error('fields');if(c.options&&(new Set(c.options.map(norm)).size!==3||!c.options.some(x=>norm(x)===norm(c.answer))))throw Error('options');return c})}
async function generate(){const topic=$('#topic').value.trim();if(!topic){$('#status').textContent=t('topic');$('#topic').focus();return}$('#make').disabled=true;$('#status').textContent=t('loading');$('#lesson').classList.add('hidden');let error;for(let attempt=0;attempt<2;attempt++){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),26000);try{const r=await fetch('/.netlify/functions/gemini',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:prompt(topic),model:'gemini-2.5-flash',temperature:attempt?.35:.5}),signal:controller.signal}),d=await r.json();if(!r.ok)throw Error(d?.error||'generation');items=validate(parse(d));index=stage=0;$('#lesson').classList.remove('hidden');$('#status').textContent='';$('#make').disabled=false;render();$('#lesson').scrollIntoView({behavior:'smooth',block:'start'});clearTimeout(timer);return}catch(e){error=e;if(!attempt)await new Promise(done=>setTimeout(done,500))}finally{clearTimeout(timer)}}console.error(error);$('#make').disabled=false;$('#status').textContent=t('error')}
function msg(s,good){$('#feedback').textContent=s;$('#feedback').className='feedback'+(good?' good':'')}
function render(){if(mode==='turn')clearRecording();const c=items[index];picked='';$('#feedback').textContent='';$('#answer').value='';$('#answer').placeholder=t('your');$('#answer').lang=target;$('#answer').dir=target==='ar'?'rtl':'auto';$('#progress').textContent=t('scenario')+' '+(index+1)+' / '+items.length;$('#sceneLabel').textContent=t('scenario');$('#scene').textContent=c.situation;$('#partnerLabel').textContent=mode==='swap'?t('model'):t('other');$('#partner').textContent=mode==='swap'?c.model:mode==='lines'?c.opening:c.partner;$('#extra').textContent=mode==='swap'?t('cue')+': '+c.cue:mode==='lines'?c.closing:'';$('#extra').classList.toggle('hidden',mode!=='swap'&&mode!=='lines');$('#meaning').textContent=mode==='lines'?'':c.meaning;$('#choices').replaceChildren();const choice=(mode==='turn'||mode==='rescue')&&stage===0;$('#instruction').textContent=choice?t('choose'):mode==='turn'&&stage===1?tt(0):mode==='turn'?tt(2):mode==='swap'?t('cue')+': '+c.cue:t('free');$('#hintText').textContent=mode==='turn'&&stage===1?([...(new Intl.Segmenter(LANG[target][2],{granularity:'word'})).segment(c.answer)].find(x=>x.isWordLike)?.segment||'')+'…':'';if(choice){for(const value of [...c.options].sort(()=>Math.random()-.5)){const b=document.createElement('button');b.className='choice';b.type='button';b.textContent=value;b.onclick=()=>{picked=value;[...$('#choices').children].forEach(x=>x.classList.toggle('selected',x===b))};$('#choices').append(b)}}$('#choices').classList.toggle('hidden',!choice);$('#answer').classList.toggle('hidden',choice);if(mode==='turn')$('#answer').maxLength=stage===1?80:280;$('#comparison').classList.add('hidden');$('#self').classList.add('hidden');$('#next').classList.add('hidden');$('#save').textContent=t('save');$('#check').classList.toggle('hidden',mode==='turn'&&stage===1);$('#reveal').textContent=mode==='turn'&&stage===1?tt(1):t('reveal');$('#check').textContent=mode==='turn'&&!choice?tt(3):choice?t('check'):t('compare');if(mode==='turn'){$('#reveal').classList.toggle('hidden',stage!==1);$('#again').textContent=tt(12);$('#listen').classList.toggle('hidden',stage===1)}}
function showModel(){const c=items[index];$('#comparison').classList.remove('hidden');$('#modelLabel').textContent=t('model');$('#listenModel').textContent=t('listen');$('#modelText').textContent=c.answer;$('#modelMeaning').textContent=c.meaning;$('#self').classList.toggle('hidden',mode==='turn');if(mode==='turn'){$('#reveal').classList.add('hidden')}$('#selfPrompt').textContent=t('self');$('#selfYes').textContent=t('works');$('#selfNo').textContent=t('repeat');$('#next').classList.remove('hidden');$('#next').textContent=index===items.length-1?t('done'):t('next')}
function check(){const c=items[index];if((mode==='turn'||mode==='rescue')&&stage===0){if(!picked){msg(t('choose'));return}if(norm(picked)!==norm(c.answer)){msg(t('retry'));return}stage=1;render();msg(t('yes'),true);return}const answer=$('#answer').value.trim();if(!answer){msg(t('your'));return}if(mode==='turn'&&stage===1){stage=2;render();showModel();msg(tt(2),true);return}showModel();if(mode==='turn'){$('#check').classList.add('hidden');const your=document.createElement('p');your.textContent=tt(6)+': '+answer;$('#comparison').prepend(your);msg(norm(answer)===norm(c.answer)?tt(4):tt(5),norm(answer)===norm(c.answer));return}msg(norm(answer)===norm(c.answer)?t('yes'):t('self'),norm(answer)===norm(c.answer))}
function next(){if(index===items.length-1){$('#lesson').classList.add('hidden');$('#status').textContent=t('done');$('#setup').scrollIntoView({behavior:'smooth'});return}index++;stage=0;render();$('#lesson').scrollIntoView({behavior:'smooth',block:'start'})}
function speak(text){const id=++playId;if(speech)speech.pause();fetch('/.netlify/functions/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,languageCode:LANG[target][2],locale:LANG[target][2]})}).then(async r=>{if(!r.ok)throw Error('tts');let src;if((r.headers.get('content-type')||'').startsWith('audio/'))src=URL.createObjectURL(await r.blob());else{const d=await r.json();src=d.url||(d.audioContent||d.audio?'data:audio/mpeg;base64,'+(d.audioContent||d.audio):'')}if(!src||id!==playId)return;speech=new Audio(src);if(src.startsWith('blob:'))speech.onended=()=>URL.revokeObjectURL(src);await speech.play()}).catch(()=>{if(id!==playId||!('speechSynthesis'in window))return;const u=new SpeechSynthesisUtterance(text);u.lang=LANG[target][2];speechSynthesis.cancel();speechSynthesis.speak(u)})}
$('#make').onclick=generate;$('#topic').addEventListener('keydown',e=>{if(e.key==='Enter')generate()});$('#answer').addEventListener('keydown',e=>{if(e.key==='Enter'){if(mode==='turn'&&stage===1)$('#reveal').click();else check()}});if(mode==='turn')$('#answer').addEventListener('input',()=>{if(stage!==1)return;const words=$('#answer').value.trim().split(/\s+/);if(words.length>4)$('#answer').value=words.slice(0,4).join(' ')});$('#check').onclick=check;$('#reveal').onclick=()=>{if(mode==='turn'&&stage===1){stage=2;render();showModel();msg(tt(2),true)}else showModel()};$('#again').onclick=()=>{stage=0;render()};$('#next').onclick=next;$('#selfYes').onclick=()=>{msg(t('yes'),true);$('#next').focus()};$('#selfNo').onclick=()=>{$('#again').focus()};$('#listen').onclick=()=>speak(mode==='swap'?items[index].model:items[index].answer);$('#listenModel').onclick=()=>speak(items[index].answer);
$('#save').onclick=()=>{const c=items[index],key='lingototal_saved_sentences_v2';let list=[];try{list=JSON.parse(localStorage.getItem(key)||'[]');if(!Array.isArray(list))list=[]}catch{}if(!list.some(x=>norm(x.sentence||x.text)===norm(c.answer)&&x.targetLanguage===LANG[target][0])){list.unshift({sentence:c.answer,translation:c.meaning,targetLanguage:LANG[target][0],targetName:LANG[target][0],source:names[mode],theme:$('#topic').value.trim(),savedAt:new Date().toISOString()});localStorage.setItem(key,JSON.stringify(list))}$('#save').textContent=t('saved')};
})();
